### ISSUE TITLE
SmartThings Presence sensor PGC410 (US model) (STSS-PRES-001)

### ISSUE THREAD

**Issue by FoxConsult** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#448]
**Device description**

SmartThings Presence sensor PGC410 (US model) (STSS-PRES-001)

**Solution**

In file /home/pi/domoticz/plugins/zigbee2mqtt/adapters/samsung/__init__.py:

Add line 'STSS-PRES-001': SensorArrival,     # SmartThings SmartThings arrival sensor

**Comment by stas-demydiuk** [comment]
Please consider switching to the next version of the plugin #458. 
Reopen this issue in case of any issues.

**Comment by FoxConsult** [comment]
Followed instructions:
cd /domoticz/plugins/zigbee2mqtt
git fetch
git checkout v3.0

Resulted in:
2020-11-08 15:47:52.051 (Zigbee2MQTT) Connected to MQTT Server: 127.0.0.1:1883
2020-11-08 15:47:52.154 (Zigbee2MQTT) Zigbee2mqtt bridge is online
2020-11-08 15:47:52.155 (Zigbee2MQTT) Joining new devices is enabled on the zigbee bridge
2020-11-08 15:47:52.155 (Zigbee2MQTT) Received available devices list from bridge
2020-11-08 15:47:52.207 (Zigbee2MQTT) Received groups list from bridge
2020-11-08 15:47:52.156 Error: (Zigbee2MQTT) 'onMessage' failed 'KeyError'.
2020-11-08 15:47:52.156 Error: (Zigbee2MQTT) ----> Line 267 in '/home/pi/domoticz/plugins/zigbee2mqtt/plugin.py', function onMessage
2020-11-08 15:47:52.156 Error: (Zigbee2MQTT) ----> Line 112 in '/home/pi/domoticz/plugins/zigbee2mqtt/plugin.py', function onMessage
2020-11-08 15:47:52.156 Error: (Zigbee2MQTT) ----> Line 167 in '/home/pi/domoticz/plugins/zigbee2mqtt/mqtt.py', function onMessage
2020-11-08 15:47:52.156 Error: (Zigbee2MQTT) ----> Line 141 in '/home/pi/domoticz/plugins/zigbee2mqtt/plugin.py', function onMQTTPublish
2020-11-08 15:47:52.156 Error: (Zigbee2MQTT) ----> Line 32 in '/home/pi/domoticz/plugins/zigbee2mqtt/devices_manager.py', function set_devices

All zigbee devices stopped working. Had to delete /domoticz/plugins/zigbee2mqtt directory and reinstall:
cd domoticz/plugins
git clone https://github.com/stas-demydiuk/domoticz-zigbee2mqtt-plugin.git zigbee2mqtt

**Comment by stas-demydiuk** [comment]
Yes, this is already fixed by one of the recent commit for #458

**Comment by FoxConsult** [comment]
No, after running "git fetch" and "git checkout v3.0", the errors I posted above started. The zigbee2MQTT plugin for Domoticz stopped working after applying #458.

**Comment by stas-demydiuk** [comment]
Could you please try to run `git pull` after switching to v3.0 branch

**Comment by FoxConsult** [comment]
Sure. Unfortunately, the error persist. Here is what I did:

sudo systemctl stop domoticz
cd /domoticz/plugins/zigbee2mqtt
git reset --hard
git fetch
git checkout v3.0 -> "Branch 'v3.0' set up to track remote branch 'v3.0' from 'origin'. Switched to a new branch 'v3.0'"
git pull -> "Already up to date."
sudo systemctl start domoticz

Domoticz log:

2020-11-09 11:30:36.960 Error: (Zigbee2MQTT) 'onMessage' failed 'TypeError':'unsupported operand type(s) for &: 'str' and 'int''.
2020-11-09 11:30:36.960 Error: (Zigbee2MQTT) ----> Line 279 in '/home/pi/domoticz/plugins/zigbee2mqtt/plugin.py', function onMessage
2020-11-09 11:30:36.961 Error: (Zigbee2MQTT) ----> Line 124 in '/home/pi/domoticz/plugins/zigbee2mqtt/plugin.py', function onMessage
2020-11-09 11:30:36.961 Error: (Zigbee2MQTT) ----> Line 167 in '/home/pi/domoticz/plugins/zigbee2mqtt/mqtt.py', function onMessage
2020-11-09 11:30:36.961 Error: (Zigbee2MQTT) ----> Line 153 in '/home/pi/domoticz/plugins/zigbee2mqtt/plugin.py', function onMQTTPublish
2020-11-09 11:30:36.961 Error: (Zigbee2MQTT) ----> Line 34 in '/home/pi/domoticz/plugins/zigbee2mqtt/devices_manager.py', function set_devices
2020-11-09 11:30:36.961 Error: (Zigbee2MQTT) ----> Line 32 in '/home/pi/domoticz/plugins/zigbee2mqtt/adapter.py', function __init__
2020-11-09 11:30:36.961 Error: (Zigbee2MQTT) ----> Line 46 in '/home/pi/domoticz/plugins/zigbee2mqtt/adapter.py', function _add_devices
2020-11-09 11:30:36.961 Error: (Zigbee2MQTT) ----> Line 109 in '/home/pi/domoticz/plugins/zigbee2mqtt/adapter.py', function add_numeric_device
2020-11-09 11:30:36.961 Error: (Zigbee2MQTT) ----> Line 78 in '/home/pi/domoticz/plugins/zigbee2mqtt/adapter.py', function _has_access

**Comment by stas-demydiuk** [comment]
@FoxConsult I've added several new commits to the plugin, could you please check. Also please make sure you use the latest dev version of zigbee2mqtt

**Comment by FoxConsult** [comment]
************-------------------********************
zigbee2mqtt used is the latest development version as of 2020-11-09:
Starting Zigbee2MQTT version 1.16.1-dev (commit #431c7f7)
************-------------------********************
Steps taken:

sudo systemctl stop domoticz
cd /domoticz/plugins/zigbee2mqtt
git reset --hard
git fetch
git checkout v3.0 -> "Branch 'v3.0' set up to track remote branch 'v3.0' from 'origin'. Switched to a new branch 'v3.0'"
git pull -> "Already up to date."
sudo systemctl start domoticz

-------------::::::::::::::::::-----------------------
Domoticz log:
2020-11-10 13:36:43.282 Error: (Zigbee2MQTT) 0xd052a80020710004: can not process binary item "battery_low"

Reason for error: SmartThings (Samsung) Motion sensor (2013 model) is missing from /samsung/__init__.py.

This is the original SmartThings (Samsung) motion sensor which is not present in /domoticz/plugins/zigbee2mqtt/adapters/samsung/__init__.py

IEEE address		Manufacturer	Model
0xd052a80020710004	SmartThings	STSS-IRM-001

Exposes:
occupancy	FALSE
battery_low	FALSE
tamper		FALSE
linkquality	126 lqi

Fix:
I addedd the line "'STSS-IRM-001': MotionAndTemperatureSensorAdapter,   # SmartThings Motion sensor (2013 model)" to /samsung/ "__init__.py" and restarted the domoticz service and the error "Error: (Zigbee2MQTT) 0xd052a80020710004: can not process binary item "battery_low" in Domoticz log is gone.

-------------::::::::::::::::::-----------------------
Domoticz log:
2020-11-10 13:36:43.282 Error: (Zigbee2MQTT) 0xd052a8005bc90005: can not process binary item "presence"

Reason for error: SmartThings (Samsung) Precense sensor (2013 model) is missing from /samsung/ "__init__.py".

This is the original SmartThings (Samsung) Precense sensor which is not present in /domoticz/plugins/zigbee2mqtt/adapters/samsung/ "__init__.py"

IEEE address		Manufacturer	Model
0xd052a8005bc90005	SmartThings	STSS-PRES-001

Exposes:
battery		N/A %
presence	TRUE
linkquality	26 lqi

Fix:
I addedd the line "'STSS-PRES-001': SensorArrival,     # SmartThings SmartThings arrival sensor (2013 model)" to /samsung/ "__init__.py" and restarted the domoticz service and the error "Error: (Zigbee2MQTT) 0xd052a8005bc90005: can not process binary item "presence"" in Domoticz log is gone.
