### ISSUE TITLE
Domoticz UI does not reflect devices status

### ISSUE THREAD

**Issue by jefdemas** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#466]
After updating domoticz to the latest beta version the devices don't get an status update in domoticz it shows in the zigbee plugin the correct latest comm.

in zigbee plugin
PIR Zolder | RTCGQ01LM | MiJia human body movement sensor | EndDevice | 0x00158d00047d262e | 2020-11-13 04:54:47

in domoticz
zigbee2mqqt | 0x00158d00047d262e_motion | 57 | PIR Zolder | Light/Switch | Switch | Off | 4 |   |   | 2020-11-08 22:07:09

all updates stoped on 2020-11-08 22:xx:xx
but the update i did was that day at 18:00.
all plugins are up to date it says.

regards

**Issue description**
Put general information here

**Additional information**
Zigbee2MQTT version: v3
Python version:
Domoticz version:
Plugin version:

**Logs**
Attach any additional logs here which might be useful: mqtt, domoticz, plugin logs

**Comment by Bartekn86** [comment]
same issiue "current_heating_setpoint":"25.0"   readed from console, 
no changes in domoticz

**Comment by Bartekn86** [comment]
reinstall solve problem

**Comment by jefdemas** [comment]
wat did you reinstall?

**Comment by Bartekn86** [comment]
raspbery os + mqtt + domoticz, all

**Comment by Bartekn86** [comment]
sorry, cache problem, 
your right, do not have update in domoticz

**Comment by jefft4** [comment]
My z2mqtt devices aren't updating the domoticz UI, nor the domoticz engine.  When I change the state of an Innr bulb, the bulb reacts correctly but the UI does not and using dzVents code to check the device status, I get the same (wrong) data as I see in the domoticz UI.

Logs etc here: https://domoticz.com/forum/viewtopic.php?f=65&t=24975&p=261957#p261957

Tried clearing cache, different browser, etc etc.  Domoticz (beta) and plugin both latest versions.

@stas-demydiuk - 'johansson' on the forum thread suggested this was fixed, but didn't give details... is there something we need to do, or is this still in fact a live bug?

**Comment by stas-demydiuk** [comment]
Please upgrade to the latest plugin and zigbee2mqtt version and check. In case the issue is still present please reopen the ticket

**Comment by stas-demydiuk** [comment]
Please provide all log you have with latest plugin as I'm not a magician to guess what could be wrong in your setup.
- lest of devices you have
- actions to reproduce the issue
- zigbee2mqtt log
- Domoticz log with plugin log (don't forget to turn on debug mode in the plugin)

**Comment by jefdemas** [comment]
log in domoticz
2021-01-17 14:43:31.855 Error: (Zigbee) ----> Line 279 in '/home/pi/domoticz/plugins/zigbee2mqtt/plugin.py', function onMessage
2021-01-17 14:43:31.855 Error: (Zigbee) ----> Line 124 in '/home/pi/domoticz/plugins/zigbee2mqtt/plugin.py', function onMessage
2021-01-17 14:43:31.855 Error: (Zigbee) ----> Line 167 in '/home/pi/domoticz/plugins/zigbee2mqtt/mqtt.py', function onMessage
2021-01-17 14:43:31.855 Error: (Zigbee) ----> Line 199 in '/home/pi/domoticz/plugins/zigbee2mqtt/plugin.py', function onMQTTPublish
2021-01-17 14:43:31.855 Error: (Zigbee) ----> Line 54 in '/home/pi/domoticz/plugins/zigbee2mqtt/devices_manager.py', function handle_mqtt_message
2021-01-17 14:43:31.855 Error: (Zigbee) ----> Line 64 in '/home/pi/domoticz/plugins/zigbee2mqtt/adapters/base_adapter.py', function handle_mqtt_message
2021-01-17 14:43:31.855 Error: (Zigbee) ----> Line 126 in '/home/pi/domoticz/plugins/zigbee2mqtt/devices/device.py', function handle_message
2021-01-17 14:43:31.855 Error: (Zigbee) ----> Line 104 in '/home/pi/domoticz/plugins/zigbee2mqtt/devices/device.py', function get_device_args
2021-01-17 14:43:31.855 Error: (Zigbee) ----> Line 41 in '/home/pi/domoticz/plugins/zigbee2mqtt/devices/light/dimmer.py', function get_numeric_value

even node red does't connect to zigbee to mqtt

**Comment by jefdemas** [comment]
pi@Domoticz:/opt/zigbee2mqtt $ npm start

> zigbee2mqtt@1.17.0 start /opt/zigbee2mqtt
> node index.js

internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module 'zigbee-herdsman-converters/lib/ota/tradfri'
Require stack:
- /opt/zigbee2mqtt/lib/extension/otaUpdate.js
- /opt/zigbee2mqtt/lib/controller.js
- /opt/zigbee2mqtt/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/opt/zigbee2mqtt/lib/extension/otaUpdate.js:6:20)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/opt/zigbee2mqtt/lib/extension/otaUpdate.js',
    '/opt/zigbee2mqtt/lib/controller.js',
    '/opt/zigbee2mqtt/index.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zigbee2mqtt@1.17.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the zigbee2mqtt@1.17.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2021-01-17T13_41_59_642Z-debug.log

**Comment by jefdemas** [comment]
i did a git pull 
/opt/zigbee2mqtt
/domoticz/plugins/zigbee2mqtt

is there some upgrade i missed?

**Comment by jefdemas** [comment]
after reboot this log shows up in domoticz

2021-01-17 14:51:24.762 Error: (Zigbee) ----> Line 124 in '/home/pi/domoticz/plugins/zigbee2mqtt/plugin.py', function onMessage
2021-01-17 14:51:24.762 Error: (Zigbee) ----> Line 167 in '/home/pi/domoticz/plugins/zigbee2mqtt/mqtt.py', function onMessage
2021-01-17 14:51:24.762 Error: (Zigbee) ----> Line 199 in '/home/pi/domoticz/plugins/zigbee2mqtt/plugin.py', function onMQTTPublish
2021-01-17 14:51:24.762 Error: (Zigbee) ----> Line 54 in '/home/pi/domoticz/plugins/zigbee2mqtt/devices_manager.py', function handle_mqtt_message
2021-01-17 14:51:24.762 Error: (Zigbee) ----> Line 64 in '/home/pi/domoticz/plugins/zigbee2mqtt/adapters/base_adapter.py', function handle_mqtt_message
2021-01-17 14:51:24.762 Error: (Zigbee) ----> Line 126 in '/home/pi/domoticz/plugins/zigbee2mqtt/devices/device.py', function handle_message
2021-01-17 14:51:24.762 Error: (Zigbee) ----> Line 104 in '/home/pi/domoticz/plugins/zigbee2mqtt/devices/device.py', function get_device_args
2021-01-17 14:51:24.762 Error: (Zigbee) ----> Line 41 in '/home/pi/domoticz/plugins/zigbee2mqtt/devices/light/dimmer.py', function get_numeric_value
2021-01-17 14:51:24.828 Error: (Zigbee) 'onMessage' failed 'TypeError':'get_numeric_value() takes 3 positional arguments but 4 were given'.
2021-01-17 14:51:24.828 Error: (Zigbee) ----> Line 279 in '/home/pi/domoticz/plugins/zigbee2mqtt/plugin.py', function onMessage
2021-01-17 14:51:24.828 Error: (Zigbee) ----> Line 124 in '/home/pi/domoticz/plugins/zigbee2mqtt/plugin.py', function onMessage
2021-01-17 14:51:24.828 Error: (Zigbee) ----> Line 167 in '/home/pi/domoticz/plugins/zigbee2mqtt/mqtt.py', function onMessage
2021-01-17 14:51:24.828 Error: (Zigbee) ----> Line 199 in '/home/pi/domoticz/plugins/zigbee2mqtt/plugin.py', function onMQTTPublish
2021-01-17 14:51:24.828 Error: (Zigbee) ----> Line 54 in '/home/pi/domoticz/plugins/zigbee2mqtt/devices_manager.py', function handle_mqtt_message
2021-01-17 14:51:24.828 Error: (Zigbee) ----> Line 64 in '/home/pi/domoticz/plugins/zigbee2mqtt/adapters/base_adapter.py', function handle_mqtt_message
2021-01-17 14:51:24.828 Error: (Zigbee) ----> Line 126 in '/home/pi/domoticz/plugins/zigbee2mqtt/devices/device.py', function handle_message
2021-01-17 14:51:24.828 Error: (Zigbee) ----> Line 104 in '/home/pi/domoticz/plugins/zigbee2mqtt/devices/device.py', function get_device_args
2021-01-17 14:51:24.828 Error: (Zigbee) ----> Line 41 in '/home/pi/domoticz/plugins/zigbee2mqtt/devices/light/dimmer.py', function get_numeric_value
2021-01-17 14:51:27.164 (Opentherm) Lighting 2 (CH_active)
2021-01-17 14:51:27.171 (Opentherm) Lighting 2 (FlameOn)

**Comment by stas-demydiuk** [comment]
For this issue, I've created a fix today: https://github.com/stas-demydiuk/domoticz-zigbee2mqtt-plugin/commit/2c96e39d4855996995adef4afe79cc83cd4a9d51

Please upgrade plugin and check again

**Comment by jefdemas** [comment]
Yes that solve the problem thx

**Comment by jefdemas** [comment]
only network map isn't showing correct there aren't any links showing only devices

**Comment by jefft4** [comment]
> Please upgrade to the latest plugin and zigbee2mqtt version and check. In case the issue is still present please reopen the ticket
Updated on Saturday.

Latest version looks okay in respect of the dimmer level, which is updated correctly, but the colour / white CCT picker still doesn't retain its state.  For example, if I choose a very warm white, the bulb is set to that colour but when I close and re-open the colour picker in the UI, the marker is in the centre of the circle, not where I set it.  If I create a dummy RGBWW switch and move the colour picker, it retains its position when I go back to it.
