### ISSUE TITLE
Update plug-in to v3.0 - Not working

### ISSUE THREAD

**Issue by Anjerlaan** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#496]
**Issue description**
Yesterday I updated the Plug-in to version v3.0 with the following commands:
```
sudo git fetch
sudo git checkout v3.0
```
Sudo was needed  (which is not with old version)

After restarting Domoticz, non of the Zigbee2MQTT devices is working properly anymore:

Domoticz device states are not updated nor respond to on/off actions (no errors are shown in domoticz log), but the bulb itself is turned on/off

The only error after restart in domoticz log is the JTYJ_GD_01LM is the "MiJia Honeywell smoke detector" device:
```
2020-12-08 14:01:36.386 Error: (Zigbee2MQTT) 'onMessage' failed 'TypeError':'__init__() missing 1 required positional argument: 'device_name_suffix''.
2020-12-08 14:01:36.386 Error: (Zigbee2MQTT) ----> Line 279 in '/home/pi/domoticz/plugins/zigbee2mqtt/plugin.py', function onMessage
2020-12-08 14:01:36.386 Error: (Zigbee2MQTT) ----> Line 124 in '/home/pi/domoticz/plugins/zigbee2mqtt/plugin.py', function onMessage
2020-12-08 14:01:36.386 Error: (Zigbee2MQTT) ----> Line 167 in '/home/pi/domoticz/plugins/zigbee2mqtt/mqtt.py', function onMessage
2020-12-08 14:01:36.386 Error: (Zigbee2MQTT) ----> Line 153 in '/home/pi/domoticz/plugins/zigbee2mqtt/plugin.py', function onMQTTPublish
2020-12-08 14:01:36.386 Error: (Zigbee2MQTT) ----> Line 27 in '/home/pi/domoticz/plugins/zigbee2mqtt/devices_manager.py', function set_devices
2020-12-08 14:01:36.386 Error: (Zigbee2MQTT) ----> Line 10 in '/home/pi/domoticz/plugins/zigbee2mqtt/adapters/lumi/JTYJ_GD_01LM.py', function __init__
2020-12-08 14:01:36.386 Error: (Zigbee2MQTT) ----> Line 8 in '/home/pi/domoticz/plugins/zigbee2mqtt/adapters/generic/smoke_sensor.py', function __init__
2020-12-08 14:01:36.386 Error: (Zigbee2MQTT) ----> Line 6 in '/home/pi/domoticz/plugins/zigbee2mqtt/devices/sensor/smoke.py', function __init__
```

Please advise

**Additional information**
Zigbee2MQTT version: 1.16.2
In configuration.yaml the following lines are added:
experimental:
new_api: true
frontend:
port: 1890

Python version: Python Version: 3.7.3 (default, Jul 25 2020, 13:03:44)
Domoticz version: 2020.2 (build 12732)
Plugin version: v3.0

**Logs**
Attach any additional logs here which might be useful: mqtt, domoticz, plugin logs

This is the domoticz log after restart: https://pastebin.com/mckJ3WQG

**Comment by Anjerlaan** [comment]
Okay after removing all Z2M devices from domoticz, uninstall plug-in with plug-in manager....and reinstall plug-in + devices
Everything seem to work normal again

**Comment by heggink** [comment]
OK, so there is no upgrade, right? Uninstall the old plugin and reinstall the new including including all devices again?

**Comment by Anjerlaan** [comment]
> OK, so there is no upgrade, right? Uninstall the old plugin and reinstall the new including including all devices again?

That is the question...I had to perform the steps tot make it work again...maybe it has to do with the sudo commands, which were not neccesary with the earlier versions

**Comment by Anjerlaan** [comment]
Strange...it seems that 0.2.1 is installed...but the plug-in directory is root owner...but i was logged in as home/pi user

**Comment by Thro42** [comment]
It is the same problem then in master branch. After update Zigbee2Mqtt to 1.16.2, the answer of the request to "bridge/config/devices" is not longer in the "bridge/log" !. File domoticz-zigbee2mqtt-plugin/api/devices.py has to chage, for extracting the Information from the "bridge/config/devices"  Message. Same problem will be in domoticz-zigbee2mqtt-plugin/api/groups.py

**Comment by Anjerlaan** [comment]
So the v3.0 version needs to be updates, with respect to zigbee2mqtt version 1.16.2?

**Comment by Thro42** [comment]
I chaged domoticz-zigbee2mqtt-plugin/api/devices.py to following Code
```
class GetDevices(APICommand):
    def execute(self, params):
        self.publish_mqtt('bridge/config/devices/get', '')

    def handle_mqtt_message(self, topic, message):
        if topic == 'bridge/log' and message['type'] == 'devices':
            self.send_response(message['message'])
            return
        if topic == 'bridge/config/devices':
            self.send_response(message)
```
That works for now

**Comment by Anjerlaan** [comment]
> I chaged domoticz-zigbee2mqtt-plugin/api/devices.py to following Code
> 
> ```
> class GetDevices(APICommand):
>     def execute(self, params):
>         self.publish_mqtt('bridge/config/devices/get', '')
> 
>     def handle_mqtt_message(self, topic, message):
>         if topic == 'bridge/log' and message['type'] == 'devices':
>             self.send_response(message['message'])
>             return
>         if topic == 'bridge/config/devices':
>             self.send_response(message)
> ```
> 
> That works for now

I have a question.
When I changed to v.3.0 (as home/pi user) with:
```
git fetch
git checkout v3.0
```
I got writing errors, so I had to use the sudo command
But now the /home/pi/domoticz/plugins/zigbee2mqtt directory is root user and all my other plugin directories are created by home/pi user.

Did you have the same sudo issue, or is your Z2M & Domoticz system created with root user?
Can this become an issue because of writing errors?

**Comment by Thro42** [comment]
Sorry but I'm not using V3.0. I only saw that there is the same problem with zigbee2mqtt version 1.16.2. I edited the file /home/pi/domoticz/plugins/zigbee2mqtt/api/devices.py via sudo. It's just a workaround for me at first.

**Comment by CyberClwn** [comment]
Check issue 499, maybe it helps you 2:
https://github.com/stas-demydiuk/domoticz-zigbee2mqtt-plugin/issues/499

**Comment by Anjerlaan** [comment]
> I chaged domoticz-zigbee2mqtt-plugin/api/devices.py to following Code
> 
> ```
> class GetDevices(APICommand):
>     def execute(self, params):
>         self.publish_mqtt('bridge/config/devices/get', '')
> 
>     def handle_mqtt_message(self, topic, message):
>         if topic == 'bridge/log' and message['type'] == 'devices':
>             self.send_response(message['message'])
>             return
>         if topic == 'bridge/config/devices':
>             self.send_response(message)
> ```
> 
> That works for now

I removed all zigbee devices and the plug-in and started from scratch 
I installed 0.2.1, my zigbee2mqtt version is 1.16.2, but it is going from bad to worse...
the plug-in does't recognize anything:

- The zigbee2mqtt manager does not list the zigbee devices (but after your above code change they are listed)

- Only the groups are imported as devices

- All other zigbee devices don't show up in the devices list

Anybody got an idea?

**Comment by Anjerlaan** [comment]
> It is the same problem then in master branch. After update Zigbee2Mqtt to 1.16.2, the answer of the request to "bridge/config/devices" is not longer in the "bridge/log" !. File domoticz-zigbee2mqtt-plugin/api/devices.py has to chage, for extracting the Information from the "bridge/config/devices" Message. Same problem will be in domoticz-zigbee2mqtt-plugin/api/groups.py

@stas-demydiuk can you check if the domoticz-zigbee2mqtt-plugin (either 0.2.1 or v3.0) have problems with zigbee2mqtt 1.16.2?
Nothing seem to work properly anymore since in 1.16.2 the answer of the request to "bridge/config/devices" is not longer in the "bridge/log"

**Comment by stas-demydiuk** [comment]
@heggink to your question yes, old version isn't fully compatible with the 3.0 one, so better is to remove the old one from hardware and after that make a plugin upgrade

**Comment by stas-demydiuk** [comment]
@Anjerlaan All issues mentioned here should be fixed now, could you please check

**Comment by sammyke007** [comment]
> @heggink to your question yes, old version isn't fully compatible with the 3.0 one, so better is to remove the old one from hardware and after that make a plugin upgrade

Does this also remove all the devices in Domoticz?!

**Comment by Dylantje** [comment]
Dear @stas-demydiuk 
I did the upgrade latest domotic latest z2m latest plugin version.
My config yaml:
`homeassistant: false
frontend:
  port: 8888
experimental:
  new_api: true
permit_join: true
log_level: error
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://localhost'
serial:
  port: /dev/ttyACM1
  disable_led: false
  channel: 11
devices:`

Still not working. this error:
`2020-12-27 20:25:46.265 Error: (DMP Z2M) 'onMessage' failed 'TypeError':''NoneType' object is not subscriptable'.
2020-12-27 20:25:46.266 Error: (DMP Z2M) ----> Line 279 in '/home/pi/domoticz/plugins/zigbee2mqtt/plugin.py'
2020-12-27 20:25:46.266 Error: (DMP Z2M) ----> Line 124 in '/home/pi/domoticz/plugins/zigbee2mqtt/plugin.py'
2020-12-27 20:25:46.266 Error: (DMP Z2M) ----> Line 167 in '/home/pi/domoticz/plugins/zigbee2mqtt/mqtt.py'
2020-12-27 20:25:46.266 Error: (DMP Z2M) ----> Line 153 in '/home/pi/domoticz/plugins/zigbee2mqtt/plugin.py'
2020-12-27 20:25:46.266 Error: (DMP Z2M) ----> Line 24 in '/home/pi/domoticz/plugins/zigbee2mqtt/devices_manager.py'`


So please help.

**Comment by sammyke007** [comment]
I don't understand what happened all of a sudden to the plugin. It still states 0.2.1 but as I read everywhere it is now unofficial 3.0?
For some reason this broke a lot of running systems with the errors mentioned above (onMessage...).

I realy would like to use my LIDL/Silvercrest power plugs, but I will wait before updating for now...

**Comment by stas-demydiuk** [comment]
@Dylantje, did you do a clean install when upgrading to 3.0 (i.e. remove plugin from hardware and then create a new instance)
