### ISSUE TITLE
Dimmer doesn't show correct % with beta 3.1

### ISSUE THREAD

**Issue by arjanvanleent** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#714]
**Issue description**
Dimmer doesn't show correct % with beta 3.1

**Additional information**
Zigbee2MQTT version: v.1.21.1 (zStack12 20190608)
Python version: 2.7.16
Domoticz version: 2021.1 (build 13499)
Plugin version: Zigbee2MQTT Plugin (v. 3.1.0-beta)

Left production Domoticz with old version of the plugin right clean Domoticz install on a different PI with beta 3.1
![image](https://user-images.githubusercontent.com/17556892/133858773-a25912ae-4cf1-4d98-9083-d6042f3757fa.png)

**Logs**
Attach any additional logs here which might be useful: mqtt, domoticz, plugin logs

**Comment by dobber81** [comment]
Same issue here. Moves back to 0% right after I change it to any %

**Comment by stas-demydiuk** [comment]
Could you please post several MQTT messages with the data your receive for this device?
Also, are there anything useful in the Domoticz log when you enable plugin debug mode?

**Comment by arjanvanleent** [comment]
I did see it  by a clean installation. Didn't try it on my production system.

Zigbee2mqtt log

`Info MQTT publish: topic 'zigbee2mqtt/links_achter_dimmer', payload '{"brightness":134,"state":"ON"}'
Info MQTT publish: topic 'zigbee2mqtt/Ikea 400lm 1', payload '{"brightness":134,"last_seen":"2021-09-20T21:28:32+02:00","linkquality":75,"power_on_behavior":null,"state":"ON","update":{"state":"idle"},"update_available":false}'
Info MQTT publish: topic 'zigbee2mqtt/woonkamer_dimmer', payload '{"brightness":134,"state":"ON"}'
Info MQTT publish: topic 'zigbee2mqtt/links_achter_dimmer', payload '{"brightness":134,"state":"ON"}'
Info MQTT publish: topic 'zigbee2mqtt/Ikea 400lm 1', payload '{"brightness":134,"last_seen":"2021-09-20T21:28:32+02:00","linkquality":75,"power_on_behavior":null,"state":"ON","update":{"state":"idle"},"update_available":false}'
Info MQTT publish: topic 'zigbee2mqtt/woonkamer_dimmer', payload '{"brightness":134,"state":"ON"}'
Info MQTT publish: topic 'zigbee2mqtt/Tuin Rechts 2', payload '{"brightness":63,"last_seen":"2021-09-20T21:28:35+02:00","linkquality":63,"state":"ON","update":{"state":"available"},"update_available":true}'`

Domoticz log

`2021-09-20 21:27:57.004 ZigBee 2 MQTT: (ZigBee 2 MQTT) Command "Set Level" from device "Ikea 400lm 1 (Light)"
2021-09-20 21:27:57.005 ZigBee 2 MQTT: (ZigBee 2 MQTT) MqttClient::publish zigbee2mqtt/Ikea 400lm 1/set ({"state": "ON", "brightness": 101})
2021-09-20 21:27:58.912 ZigBee 2 MQTT: (ZigBee 2 MQTT) [Command] Device 0x000d6ffffefd10de(1): Off(level = 0, color = )
2021-09-20 21:27:58.939 ZigBee 2 MQTT: (ZigBee 2 MQTT) Command "Off" from device "Ikea 400lm 2 (Light)"
2021-09-20 21:27:58.940 ZigBee 2 MQTT: (ZigBee 2 MQTT) MqttClient::publish zigbee2mqtt/Ikea 400lm 2/set ({"state": "OFF"})
2021-09-20 21:27:59.951 ZigBee 2 MQTT: (ZigBee 2 MQTT) [Command] Device 0x000d6ffffefd10de(1): On(level = 0, color = )
2021-09-20 21:27:59.994 ZigBee 2 MQTT: (ZigBee 2 MQTT) Command "On" from device "Ikea 400lm 2 (Light)"
2021-09-20 21:27:59.994 ZigBee 2 MQTT: (ZigBee 2 MQTT) MqttClient::publish zigbee2mqtt/Ikea 400lm 2/set ({"state": "ON"})
2021-09-20 21:28:02.071 ZigBee 2 MQTT: (ZigBee 2 MQTT) [Command] Device 0x000d6ffffefd10de(1): Set Level(level = 27, color = )
2021-09-20 21:28:02.132 ZigBee 2 MQTT: (ZigBee 2 MQTT) Command "Set Level" from device "Ikea 400lm 2 (Light)"
2021-09-20 21:28:02.133 ZigBee 2 MQTT: (ZigBee 2 MQTT) MqttClient::publish zigbee2mqtt/Ikea 400lm 2/set ({"state": "ON", "brightness": 68})
2021-09-20 21:28:06.302 ZigBee 2 MQTT: (ZigBee 2 MQTT) [Command] Device 0x000b3cfffef56a4b(1): Set Level(level = 48, color = )
2021-09-20 21:28:06.363 ZigBee 2 MQTT: (ZigBee 2 MQTT) Command "Set Level" from device "lamp 2_1 (Light)"
2021-09-20 21:28:06.364 ZigBee 2 MQTT: (ZigBee 2 MQTT) MqttClient::publish zigbee2mqtt/lamp 2_1/set ({"state": "ON", "brightness": 121})
2021-09-20 21:28:32.820 ZigBee 2 MQTT: (ZigBee 2 MQTT) [Command] Device 0x000d6ffffefd94fc(1): Set Level(level = 53, color = )
2021-09-20 21:28:32.868 ZigBee 2 MQTT: (ZigBee 2 MQTT) Command "Set Level" from device "Ikea 400lm 1 (Light)"
2021-09-20 21:28:32.868 ZigBee 2 MQTT: (ZigBee 2 MQTT) MqttClient::publish zigbee2mqtt/Ikea 400lm 1/set ({"state": "ON", "brightness": 134})`

**Comment by devrosx** [comment]
looks like its related to my bugreport 
https://github.com/stas-demydiuk/domoticz-zigbee2mqtt-plugin/issues/726

**Comment by Bartole** [comment]
I can confirm similar behavior. When using domoticz gui to change dimmer level using the slider the level changes as desired, but the slider pops back to the previous position. It does work properly with non-zigbee dimmers in Domoticz and also when using the dashboard of zigbee2mqtt, so it seems to point at this plugin.

Side effect is also that groups containing zigbee devices do 'think' devices are still on, although they have been turned off which results in some scripts behaving oddly (no mixed status in those groups).

Updating this morning to #cf68507 did not fix it :-(.

Gr,
Bart

**Comment by stas-demydiuk** [comment]
Raised the issue in Domoticz repository #5010, hopefully someone will be able to take a look

**Comment by stas-demydiuk** [comment]
Should be fixed now, could you please update plugin and check

**Comment by Bartole** [comment]
I updated the plugin, but issue persists.

Gr,
Bart

**Comment by stas-demydiuk** [comment]
That sounds a bit odd, could you please double-check that you have the latest plugin version from the master branch

**Comment by Bartole** [comment]
I know, I checked for the code changes to be present and they are. Updated it just now to #db397ad, but I still have the same issue. Will experiment with recreating devices.

**Comment by Bartole** [comment]
Recreating device did not help I will experiment further. Happy Christmas!

**Comment by Bartole** [comment]
My hunch is that I use I 'pure' dimmer (no colortemp) and I assume that in that case dimmer.py is involved and not ct.py and dimmer.py has not been touched. Will try to add code to dimmer.py when I find the correct spot.

**Comment by Bartole** [comment]
I (too) crudely added "domoticz_device.LastLevel = Level" to plugin.py and with this it works (I did not yet manage to modify dimmer.py).

    def onCommand(self, device_id, unit, command, Level, Color):
        domoticz.debug("[Command] Device " + device_id + '(' + str(unit) + '): ' + command + "(level = " + str(Level) + ", color = " + Color + ')')

        message = None
        domoticz_device = domoticz.get_device(device_id, unit)
        domoticz_device.LastLevel = Level
        zigbee_device_alias = configuration.get_zigbee_feature_data(device_id, unit)

**Comment by bizziebis** [comment]
I'm also having problems with regular dimmers not showing the actual dimmer value. I used the fix fromBartole, but this will only work when setting the dimmer slider manually. It still doesn't update the value when the dimmer is set by eg. the event system, or externally.

Is there anything I can do help to debug the issue?

**Comment by odelma** [comment]
Hi, looks like majority of zigbee dimmers are now showing the dim level correct in GUI. Not sure at which point this changed but very good 👍 😄 

One item that still has the "old" behavior (dim level springs back to zero) are zigbee groups - at least my newly created _ct -group with IKEA GU10 bulbs. If I dim it, this shows in zigbee2mqtt logs:
```
Info MQTT publish: topic 'zigbee2mqtt/Autotallin etuseinä 1', payload '{"brightness":33,"color_mode":"color_temp","color_temp":333,"linkquality":0,"power_on_behavior":null,"state":"ON"}'
Info MQTT publish: topic 'zigbee2mqtt/Etuseinä_ct', payload '{"brightness":33,"color_mode":"color_temp","color_temp":333,"state":"ON"}'
Info MQTT publish: topic 'zigbee2mqtt/Autotallin etuseinä 2', payload '{"brightness":33,"color_mode":"color_temp","color_temp":333,"linkquality":60,"power_on_behavior":null,"state":"ON"}'
Info MQTT publish: topic 'zigbee2mqtt/Etuseinä 1 alas', payload '{"brightness":33,"color_mode":"color_temp","color_temp":333,"linkquality":3,"power_on_behavior":null,"state":"ON"}'
Info MQTT publish: topic 'zigbee2mqtt/Etuseinä 2 alas', payload '{"brightness":33,"color_mode":"color_temp","color_temp":333,"linkquality":12,"power_on_behavior":null,"state":"ON"}'
Info MQTT publish: topic 'zigbee2mqtt/Etuseinä 1 ylös', payload '{"brightness":33,"color_mode":"color_temp","color_temp":333,"linkquality":18,"power_on_behavior":null,"state":"ON"}'
Info MQTT publish: topic 'zigbee2mqtt/Etuseinä 2 ylös', payload '{"brightness":33,"color_mode":"color_temp","color_temp":333,"linkquality":30,"power_on_behavior":null,"state":"ON"}'
Info MQTT publish: topic 'zigbee2mqtt/Etuseinä 3 alas', payload '{"brightness":33,"color_mode":"color_temp","color_temp":333,"linkquality":66,"power_on_behavior":null,"state":"ON"}'
Info MQTT publish: topic 'zigbee2mqtt/Etuseinä 3 ylös', payload '{"brightness":33,"color_mode":"color_temp","color_temp":333,"linkquality":75,"power_on_behavior":null,"state":"ON"}'
Info MQTT publish: topic 'zigbee2mqtt/Etuseinä 4 alas', payload '{"brightness":33,"color_mode":"color_temp","color_temp":333,"linkquality":72,"power_on_behavior":null,"state":"ON"}'
Info MQTT publish: topic 'zigbee2mqtt/Etuseinä 4 ylös', payload '{"brightness":33,"color_mode":"color_temp","color_temp":333,"linkquality":18,"power_on_behavior":null,"state":"ON"}'
Info MQTT publish: topic 'zigbee2mqtt/Etuseinä 5 alas', payload '{"brightness":33,"color_mode":"color_temp","color_temp":333,"linkquality":0,"power_on_behavior":null,"state":"ON"}'
Info MQTT publish: topic 'zigbee2mqtt/Etuseinä 5 ylös', payload '{"brightness":33,"color_mode":"color_temp","color_temp":333,"linkquality":0,"power_on_behavior":null,"state":"ON"}'
Info MQTT publish: topic 'zigbee2mqtt/Etuseinä_alas_ct', payload '{"brightness":33,"color_mode":"color_temp","color_temp":333,"state":"ON"}'
Info MQTT publish: topic 'zigbee2mqtt/Etuseinä_ylös_ct', payload '{"brightness":33,"color_mode":"color_temp","color_temp":333,"state":"ON"}'
```
The individual devices (bulbs) go to and remain on correct dim level, but the group device dim level goes back to 0.
@stas-demydiuk

**Comment by stas-demydiuk** [comment]
Hopefully now should be fixed for regular dimmers as well. Could someone please upgrade the plugin and check

**Comment by odelma** [comment]
Hi, I did a git pull and should be in the latest version. Also restarted Domoticz, cleared caches etc. Still the behavior of the zigbee _ct group at least is the same. Dimming level is not visible on the GUI.
![image](https://user-images.githubusercontent.com/10372952/152739849-79ad188c-46c8-435d-86cf-00b9e17e9f77.png)

Should I update zigbee2mqtt bridge to latest version as well (it is not updated for at least a few weeks)?

**Comment by stas-demydiuk** [comment]
@odelma, are you talking about dimers related to zigbee groups or regular dimmers from actual devices?

**Comment by odelma** [comment]
Hi, sorry for being unclear. This was about a zigbee group of _ct devices. Regular zigbee dimmers are working ok in my setup but this group is not reflecting the set dim status. I think the info is available in mqtt messages, e.g.
`MQTT publish: topic 'zigbee2mqtt/Etuseinä numero_ct', payload '{"brightness":81,"color_mode":"color_temp","color_temp":294,"state":"ON"}'`

I thought it was in general about the same issue mentioned here, but would have been more clear to open a separate issue of course...

**Comment by Bartole** [comment]
Raspbian Buster, kernel 5.10.63-v7+
Domoticz 2022.1 build 14161
Python 3.7.3
Zigbee2MQTT plugin v. 3.1.0-beta (#46839db)
Zigbee2MQTT 1.23.0 (#6ea61ba)

To add information and hopefully not confuse more... Zigbee dimmers (those added by the Z2M plugin) are now keeping their new dimlevel when changed, so that is good!

I still observed something that is not working as expected and maybe it is related or it may be a completely new issue.

Observation: Status of group/scene with two Z2M plugin dimmers does not get updated when individually switching dimmers inside the group (on, off or mixed). It keeps the status it had before.

Expected behavior:
- Group/scene gets 'mixed' status if one dimmer is on and the other is off.
- Group/scene get 'on' status when both dimmers are on
- Group/scene get 'off' status when both dimmers are off

Testing the same with dummy device dimmers does have the expected behavior.

**Comment by odelma** [comment]
What @Bartole above explains, corresponds to my obesrvations in previous posts under this issue (e.g. https://github.com/stas-demydiuk/domoticz-zigbee2mqtt-plugin/issues/714#issuecomment-1031169992). So zigbee groups are still having the odd behavior of not reflecting the dim level (or color picker / color temp). Not sure if it is related, I also observed that when group status is changed from Domoticz group device, it control all the lights in the group correctly in real life and in Zigbee2Mqtt dashboard, but in Domoticz the status of all lights in the group is not updating.

**Comment by stas-demydiuk** [comment]
@odelma / @Bartole, I've pushed a fix, hopefully that will help

**Comment by odelma** [comment]
> @odelma / @Bartole, I've pushed a fix, hopefully that will help

Excellent 👍 I can verify on mybehalf it is working as expected now - even with zigbee groups.

**Comment by odelma** [comment]
@stas-demydiuk - sorry to come back to this but I noticed one additional device, ”blinds percentage” which does not show the correct level in GUI.
